language: "node_js"

node_js:
  - 8
  - "lts/*"
  - "node"

install:
  - npm install -g codecov
  - npm install

script:
  - npm run lint
  - ./bin/santas-de-roy.js p1 p2 p3
  - npm run test-cov && codecov